sudo: false
language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
before_install:
  - gem update --system
  - gem install bundler -v 2.2.5
  - gem --version
install:
  - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
